language: bash

os:
- linux

env:
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4

matrix:
  include:
    - os: osx

services:
  - docker

script:
- bash -c 'time bin/bats --tap test'
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
    docker build --build-arg bashver=${BASHVER} --tag bats/bats:bash-${BASHVER} .
    docker run -it bats/bats:bash-${BASHVER} --tap /opt/bats/test
  fi

notifications:
  email:
    on_success: never
